### ISSUE TITLE
Cant edit Hour and minute in input field

### ISSUE THREAD

**Issue by iamakashaher** [danielmoncada/date-time-picker#17] opened 2020-02-28 10:56 UTC
I've implemented an owl-date-time picker but I've issue while entering hours and seconds manually.
I always need to click on up and down arrows.

```html
<input class="form-control" placeholder="Trigger Execution Start Time" id="fromTime" name="fromTime"
                  [(ngModel)]="fromTime" [owlDateTimeTrigger]="dt1" [owlDateTime]="dt1"
                  style="width: 370px;" #triggerFromDateRef="ngModel" required>
                <div class="left" style="width: max-content;">
                  <span *ngIf="triggerFromDateRef.invalid && (triggerFromDateRef.dirty || triggerFromDateRef.touched)">
                    <span *ngIf="triggerFromDateRef.errors.required" class="error">
                      Please Enter Trigger Start Date
                    </span>
                  </span>
                </div>
                <owl-date-time #dt1 [hour12Timer]="true"></owl-date-time>
```

**Comment by danielmoncada** [comment] 2020-03-02 02:02
@iamakashaher what's the issue / error you are getting? I cannot reproduce this using the demo

**Comment by iamakashaher** [comment] 2020-03-02 05:49
my edit date time is not working, i've to click on arrow to set time

**Comment by danielmoncada** [comment] 2020-03-02 15:24
@iamakashaher is there anyway you can reproduce this so I can test out?
I can't seem to reproduce it.

Also, are there any console errors?

**Comment by iamakashaher** [comment] 2020-03-03 12:30
**I'm not able to edit these fields directly!
Every time I click on that up-down arrows to set time.**

![imageedit_2_3827549220](https://user-images.githubusercontent.com/44964180/75775791-be657400-5d78-11ea-88fe-10e4f215db3c.gif)

**Comment by danielmoncada** [comment] 2020-03-03 16:55
@iamakashaher right, I understand the problem. I'm asking if there are any browser console errors? If you are using chrome, bring up the dev tools console, then try editing the date/time manually.

**Comment by iamakashaher** [comment] 2020-03-04 07:11
Hi @danielmoncada,

I checked the console for errors but I didn't find any error. is there anything which can override its properties.

**Comment by danielmoncada** [comment] 2020-06-13 04:47
@iamakashaher still having the issue? I'm able to edit the fields directly via the TextBox in the drop down. If you pull the demo down from this repo, you can see that it works here.

**Comment by danielmoncada** [comment] 2020-06-16 05:35
Closing, as this appears to be abandoned.

**Closed by danielmoncada** 2020-06-16 05:35 UTC
