### ISSUE TITLE
Issue when time picker value change

### ISSUE THREAD

**Issue by dhavalsolankislk** [danielmoncada/date-time-picker#34] opened 2020-04-09 05:37 UTC
Hello,

We are using date-time-picker in our application. We have a problem that when we are facing a issue that when we are changing time picker value and click on set button with in  500ms the value is not reflected. So in the datepicker text field value of minutes or hour which we have set remains as it is and the new value is not reflected.

**Comment by kamlesh0606** [comment] 2020-05-06 07:10
@danielmoncada  - Any Update ?

**Comment by danielmoncada** [comment] 2020-05-06 07:27
@dhavalsolankislk is the new value reflected AFTER 500ms?

**Comment by dhavalsolankislk** [comment] 2020-05-06 07:30
@danielmoncada 
New value is reflected after 1000ms

**Comment by danielmoncada** [comment] 2020-05-06 07:32
Okay, thanks @dhavalsolankislk . I'll look into this later today (it's almost 1AM here).
Any reason why you need to have it reflect right away?

**Comment by dhavalsolankislk** [comment] 2020-05-06 07:51
@danielmoncada 
We need to reflect right away as here text field of minute and set button is very near, so our client instantly click on set button after setting value of minutes within 500ms

Attaching the snap of it 
![date](https://user-images.githubusercontent.com/59446200/81149727-64617480-8f9c-11ea-9d0b-1410f23d2eff.PNG)

**Comment by dhavalsolankislk** [comment] 2020-05-08 06:46
@danielmoncada 
any update ?

**Comment by dhavalsolankislk** [comment] 2020-06-12 18:27
Hello,
@danielmoncada 
Our html code is as below

<div class="form-group mr-2">
                <label class="control-label"> {{'To'|translate}} *</label>
                <div class="input-inside-btn input-inside-btn-style-1">
                    <input class="form-control" [owlDateTimeTrigger]="dt2" placeholder="DD-MM-YYYY HH:MM"
                        [owlDateTime]="dt2" formControlName="toDate">
                    <owl-date-time [pickerType]="'both'" #dt2></owl-date-time>
                    <button type="button" class="btn btn-icon-none" [owlDateTimeTrigger]="dt2">
                        <i class="ik-l-55 micon-calendar overlap-icon color-primary"></i>
                    </button>
                </div>
            </div>

Not specific code in ts file

**Comment by danielmoncada** [comment] 2020-06-13 04:40
@dhavalsolankislk thanks for the snippet.

As per your link, which example is the issue occurring at? When I change the time and immediately click SET, it's reflected in the TextBox right away (and not haver 1000 ms).

**Comment by kamlesh0606** [comment] 2020-06-19 20:06
Hi,
@danielmoncada Problem generated below photo with given link (https://danielykpan.github.io/date-time-picker/)

![image](https://user-images.githubusercontent.com/3240948/85175660-92252300-b295-11ea-97c9-b2ca4a63c0ae.png)

Video For above problem: 
[screen-capture.zip](https://github.com/danielmoncada/date-time-picker/files/4806526/screen-capture.zip)

**Comment by allyen** [comment] 2020-06-23 14:38
This is caused by https://github.com/danielmoncada/date-time-picker/blob/master/projects/picker/src/lib/date-time/timer-box.component.ts#L85. If you click 'Set' before the debunceTime elapses, the value is not persisted. I believe the debounceTime could be safely removed since the user can write only two numbers and furtheremore no complex logic takes place after the time is set.

**Comment by danielmoncada** [comment] 2020-06-25 01:33
fixed with https://github.com/danielmoncada/date-time-picker/pull/53

**Closed by danielmoncada** 2020-06-25 01:33 UTC
Labels: investigate
